runtime: python27
api_version: 1
threadsafe: true
service: default

# satisfy flask deps
libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: ssl
  version: latest

handlers:
- url: /callback
  script: main.app
- url: /.*
  script: main.app
  login: admin
